<?php
namespace App\Controller\Admin;

use App\Controller\AppController;
use Cake\ORM\TableRegistry;
use Cake\I18n\FrozenTime;


class SuiviTacheController extends AppController
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->Auth->allow(['index']);
        $user = $this->Auth->user();
        if($user){
            $user['confirmed_at'] = new FrozenTime($user['confirmed_at']);
            $user['reset_at'] = new FrozenTime($user['reset_at']);
            $this->set('user', $user);
        }else{
            $this->redirect(['controller' => 'Users','action' => 'logout']);
        }

    }

    public function index(){
        $tachesTable = TableRegistry::get('Taches');
        $taches = $tachesTable->find()
                    ->select(['Projets.titre', 'Taches.id', 'Taches.titre', 'Taches.debut', 'Taches.fin', 'Taches.priorite', 'Taches.remarque', 'Taches.etat'])
                    ->leftJoin(
                        ['Projets' => 'projets'],
                        ['Projets.id = Taches.id_projet']
                    )
                    ->all();
        $this->set('taches', $taches);

        return $this->render('index', 'Admin/default');
    }
}